### ISSUE TITLE
Freeze and duplicated nodes problem in epiphany-browser 

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/node-red-contrib-revpi-nodes#11]
https://revolution.kunbus.de/forum/viewtopic.php?f=6&t=2580#p9477

There is a report about unwanted duplication of nodes and program freezes, needs to be reproduced and analysed.

**Comment by dfilsinger-erminas** [comment]
We could not reproduce it with version 1.0.9 and server 1.0.4.
