### ISSUE TITLE
Suggestions on areas to fix/enchance (fixed polling interval)

### ISSUE THREAD

**Issue by halcyon0606** [erminas/node-red-contrib-revpi-nodes#12]
Firstly, I noticed that there is an issue with the node red inject node when the revpi node package is there. It causes the inject node to not display the drop down menu when the repeat interval option is set to anything other than none. Below is a picture of the issue:

![image](https://user-images.githubusercontent.com/75771253/103992843-a0348580-518c-11eb-9640-ed2889a9235b.png)

Another thing to note (not really an issue), I have noted that the single-input node works with a report by change mechanism, and the fastest rate in which it does so depends on the sampling frequency set in PiCtory. On that note, would it be possible to include an option to poll instead of report by change? So that a fixed interval can be achieved when getting the data out of the pin node. 

Thanks!

**Comment by jgerlach-erminas** [comment]
Hi,
thanks for your suggestions. The injection node problem sounds similar to this https://github.com/erminas/node-red-contrib-revpi-nodes/issues/8 
I have taken note of your feature request with a fixed polling interval for single input nodes. As a workaround in the meantime you can use the get-pin node with a custom interval/injection node in node RED.

**Comment by halcyon0606** [comment]
Ahh, I must have missed out on that issue, didn't mean to make a duplicate issue, my bad. And also thank you for the workaround! Will get working on that.

**Comment by bpfel** [comment]
Hi,

I just switched to the get-pin node with a custom interval/injection node. Currently I am reading 4 AI Pins and a single RTD pin. With that setup I can get to sampling rates of about 5Hz without getting significant lag on the dashboard UI. 

Is that expected behaviour? What kind of framerates do you usually realize and how can I optimize my flows?

Thanks for you help!

**Comment by hbunjes** [comment]
5Hz is a sampling rate that is expected to work. 

@halcyon0606 We cannot reproduce the issue with the drop down. If it still exists, please reopen the ticket with a instruction how we can reproduce this issue. Thank you!
