### ISSUE TITLE
Unstable behaviour

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/node-red-contrib-revpi-nodes#14]
https://revolution.kunbus.de/forum/viewtopic.php?f=48&t=2482#p9835

User bigmanvstrashman described some unstable behaviour:

- crashing
- pin dropdown disappearing (needs to restart flow)
- not able to rising/falling edge DO more than 2 secondes

**Comment by dfilsinger-erminas** [comment]
Is fixed with Nodes Version 1.0.9 and Server Version 1.0.4
