### ISSUE TITLE
node-red-contrib-revpi-nodes 1.0.7-X connects with Protcol WSS with required TLS by default

### ISSUE THREAD

**Issue by sklein-leogistics** [erminas/node-red-contrib-revpi-nodes#18]
The revpi-server is running on port 8000 via HTTP by default and the node tries to connect with WSS and fails because no TLS could be established.

There is no option to disable TLS and just communicate unencrypted to localhost.

![image](https://user-images.githubusercontent.com/90382934/136116947-84b2e2a2-0ded-4948-a8f9-9e89290bfa85.png)

A fallback to npm i node-red-contrib-revpi-nodes@1.0.6-1 fix the issue.

**Comment by dfilsinger-erminas** [comment]
we could not reproduce it with version 1.0.9 and server in version 1.0.4.
