### ISSUE TITLE
Single Input Node - Changing to Multi

### ISSUE THREAD

**Issue by h2oil** [erminas/node-red-contrib-revpi-nodes#2]
After a few restarts/power cycles of RevPi I had two of the single nodes change without intervention to a multi input node.

**Comment by crismancich** [comment]
That is strange. Can you send us the flow please? We will try to reproduce that.

**Comment by dfilsinger-erminas** [comment]
It has been fixed in the new versions.
We could not reproduce it with version 1.0.9 and server 1.0.4.
