### ISSUE TITLE
Serial Connection Question

### ISSUE THREAD

**Issue by gelinger777** [erminas/node-red-contrib-revpi-nodes#21]
Sorry for dumb question, but is it also possible to send and accept data on Serial RS232 Port which exists on the main RevPi device or for that I have to use the Serial Input and Output of the Node Red itself ? Sorry for opening a ticket , but I would appreciate an advise. 
Thank you very much beforehand.

**Comment by hbunjes** [comment]
Hi,
you mean a serial port which is accessible on the device directly via e.g. tty device? 

You can look for https://flows.nodered.org/node/node-red-node-serialport if this fulfills your need. This is nothing special to the RevPi.

Best
Hilmar

**Comment by hbunjes** [comment]
@gelinger777 I assume after 3 month you have tried the serialport node successfully and close this issue.

**Comment by gelinger777** [comment]
@hbunjes  sorry for late reply, yes, we have figured it out
