### ISSUE TITLE
Input pin I_1 change make I_10 to I_14 to send the same message

### ISSUE THREAD

**Issue by Hack4day** [erminas/node-red-contrib-revpi-nodes#4]
I have a problem that whenever Input I_1 changed (msg.payload from zero to one), the other input stated from Input I_10 to I_14 send the same message.
![Capture PNG2](https://user-images.githubusercontent.com/48713510/74924458-1c9f6800-5405-11ea-805c-77e40a6065e0.PNG)

**Comment by jgerlach-erminas** [comment]
Hi, thanks for the report. We are looking into it.

**Comment by jgerlach-erminas** [comment]
fixed with https://github.com/erminas/node-red-contrib-revpi-nodes/commit/2952d9a97411138019c12658c991a8c0622b4e6e

**Comment by Hack4day** [comment]
Many thanks, it worked like a charm!
