### ISSUE TITLE
Feature Request: topic

### ISSUE THREAD

**Issue by Putzeimer** [erminas/node-red-contrib-revpi-nodes#5]
Hi,
please add a topic field to the node configuration, as with most other nodes.
Thanks.

**Comment by jgerlach-erminas** [comment]
Hi,
topics are supported since [version 1.0.4](https://github.com/erminas/node-red-contrib-revpi-nodes/commit/2952d9a97411138019c12658c991a8c0622b4e6e). Do you miss something  in particular?

**Comment by Putzeimer** [comment]
Hi,
ah OK, but if I see correctly, the value of the topic is set by the node, e.g. "revpi/single/I_1". I need to specify it by myself. The revpi-single-input (same for revpi-multiple-input and revpi-getpin) is connected to a subflow. The input of the subflow has a switch which knows for example the topics "A", "B", and "C". The RevPi pins 1, 4, 7, etc have the topic "A", 2, 5, 8 equals "B" and 3, 6, 9 is set to "C".
I would like to have an input field to specify the topic in the nodes property, like in other nodes (inject, dashboard inputs, tcp in, etc). Otherwise I need a change node after every single-input to overwrite the topic.

Btw: I'm using 1.0.6.

**Comment by jgerlach-erminas** [comment]
Hi,
we have added your manual setting for topics as a feature request. I can't promise that it will be included in the next release, but I will let you know if there are updates. Thanks for the feedback

**Comment by jgerlach-erminas** [comment]
The manual topic feature will be included in the upcoming release of 1.0.8 https://github.com/erminas/node-red-contrib-revpi-nodes/releases/tag/1.0.8 There is a prebuilt debian package in the release if you want to "beta test" the solution. You would also need version 1.0.3 of the server https://github.com/erminas/noderedrevpinodes-server/releases/tag/1.0.3
