### ISSUE TITLE
Nodes change behavior of inject node

### ISSUE THREAD

**Issue by Putzeimer** [erminas/node-red-contrib-revpi-nodes#8]
Hi,
since updating to Node-RED version 1.2.3 (coming from 1.0.6), I experienced some issues with the inject node.
If I set the option "Repeat" to anything than "none", no additional options apear.
I searched the web and found this post on the official Node-RED forum:
[https://discourse.nodered.org/t/inject-node-issue-interval-settings-missing-when-interval-selected/26482](https://discourse.nodered.org/t/inject-node-issue-interval-settings-missing-when-interval-selected/26482)
The first answer from user @knolleary says:
`I wonder if there is a contrib node that is polluting the editor in someway that breaks this. It's the only thing I can think of.`
I think he is right. 

One after another, I removed my contrib packages, restarted Node-RED, refreshed the page without cache and checked the inject node again. After removing node-red-contrib-revpi-nodes, the missing options in the inject node reappeared. I double tested by installing again and the result remains the same: If node-red-contrib-revpi-nodes is installed and active, the inject node is broken.
The topic poster from the link above do have node-red-contrib-revpi-nodes installed too, as you can see in the post immediately after knolleary's post. So I think, he has the same problem.

Could you fix this problem with priority, please? The inject node is a very important node, so node-red-contrib-revpi-nodes is not usable with newer versions of Node-RED. But how to access the RevPi nodes in the meantime? The only way I can think of, is a downgrade of Node-RED. The inject node was updated in Node-RED 1.1.0-beta.1, so the newest version usable so long is 1.0.6 from april 24th.

**Comment by jgerlach-erminas** [comment]
Thank you for reporting this bug. There is also this thread https://revolution.kunbus.de/forum/viewtopic.php?f=48&t=2488 with more information. We will try to reproduce and fix this bug

**Comment by jgerlach-erminas** [comment]
This will be fixed in the upcoming release of 1.0.8 https://github.com/erminas/node-red-contrib-revpi-nodes/releases/tag/1.0.8 There is a prebuilt debian package in the release if you want to "beta test" the solution. You would also need version 1.0.3 of the server https://github.com/erminas/noderedrevpinodes-server/releases/tag/1.0.3

**Comment by Putzeimer** [comment]
Thx, I just installed noderedrevpinodes-server v1.0.3, but I get stuck on installing node-red-contrib-revpi-nodes v1.0.8. The package depends on node-ws which in turn depends on libnode64. If I try to install that, it says that nodejs will be removed. That would be bad.
Any idea?

**Comment by jgerlach-erminas** [comment]
Hi, when did you download the debian package? I have updated it on Wednesday with a fix for just this problem

**Comment by Putzeimer** [comment]
Yes, that's it. Thx.
I downloaded both, server and nodes-package, on the day you fixed it. It works like a charm with the newly downloaded packages. After failing again yesterday, I tried noderedrevpinodes-server v1.0.2 and node-red-contrib-revpi-nodes v1.0.7, but ran into the same issue.
Maybe a good idea to increase the version next time.
Fix confirmed.
