### ISSUE TITLE
Transferring input values from Node-red to Logi.cal

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/node-red-contrib-revpi-nodes#9]
https://revolution.kunbus.de/forum/viewtopic.php?f=48&t=2533&p=9419&hilit=Logi+cal+mqtt#p9419

It would be nice to transfer input values from the RevPi Nodes/Node Red to Logi.cal. There is a problem using Virtual Devices/Modules in pictory, multiple proccesses accessing the proccess image concurrently.

We have to check if there is a solution for the virtual device problem (eg. allowing the change of input variables) or if we want to offer an offical way for alternative communication (mqtt, tcp)

**Comment by hbunjes** [comment]
Customer is using MQTT for data transfer now. This is a sufficient solution and also usable for similar cases.
